USE [QuattroCafe];
GO

BEGIN TRANSACTION;

MERGE [QuattroCafe].[dbo].[Products] AS target
USING (
    SELECT
        CASE
            WHEN raw.ProductName IS NULL THEN NULL
            ELSE LEFT(raw.ProductName, COALESCE(lengths.ProductNameMax, LEN(raw.ProductName)))
        END AS ProductName,
        raw.CategoryId,
        CASE
            WHEN raw.Description IS NULL THEN NULL
            ELSE LEFT(raw.Description, COALESCE(lengths.DescriptionMax, LEN(raw.Description)))
        END AS Description,
        CASE
            WHEN raw.Tooltip IS NULL THEN NULL
            ELSE LEFT(raw.Tooltip, COALESCE(lengths.TooltipMax, LEN(raw.Tooltip)))
        END AS Tooltip,
        raw.Price,
        CASE
            WHEN raw.Image IS NULL THEN NULL
            ELSE LEFT(raw.Image, COALESCE(lengths.ImageMax, LEN(raw.Image)))
        END AS Image,
        raw.IsFeatured
    FROM (VALUES
    (N'Americano', 8, N'Espresso bazlı, sade ve dengeli içimli sıcak kahve.', N'Yeni', 150, N'americano-sıcakkkahve.jpg', 0),
    (N'Butter Caramel', 8, N'Tereyağlı karamel aromasıyla yumuşak ve tatlı içim.', N'Yeni', 180, N'caramel-latte-sıcakkahve.jpg', 0),
    (N'Cappuccino', 8, N'Bol köpük ve yoğun espresso tadıyla klasik cappuccino.', N'Yeni', 200, N'cappucino-sıcakkkahve.jpg', 0),
    (N'Caramel Latte', 8, N'Karamel dokunuşlu latte; kremamsı ve tatlı içim.', N'Yeni', 180, N'caramel-latte-sıcakkahve.jpg', 0),
    (N'Caramel Macchiato', 8, N'Espresso ve sütün karamel ile katmanlı, aromalı buluşması.', N'Yeni', 180, N'caramel-latte-sıcakkahve.jpg', 0),
    (N'Cookie Latte', 8, N'Kurabiye aromasıyla tatlı, yumuşak içimli latte.', N'Yeni', 180, N'cookie-latte-sıcakkahve.jpg', 0),
    (N'Cortado', 8, N'Espresso ve az sütle dengelenmiş, yoğun aromalı içim.', N'Yeni', 150, N'cortado-sıcakkkahve.jpg', 0),
    (N'Espresso', 8, N'Kısa, yoğun ve aroması yüksek klasik espresso.', N'Yeni', 80, N'espresso-sıcakkahve.jpg', 0),
    (N'Espresso Double', 8, N'Daha yoğun kahve deneyimi için çift shot espresso.', N'Yeni', 100, N'espresso-sıcakkahve.jpg', 0),
    (N'Flatwhite', 8, N'Kadifemsi süt dokusu ve yoğun espresso dengesi.', N'Yeni', 170, N'flatwhite-sıcakkkahve.jpg', 0),
    (N'Hazelnut Latte', 8, N'Fındık aromasıyla zenginleşen kremalı latte.', N'Yeni', 180, N'hazelnut-latte-sıcakkahve.jpg', 0),
    (N'Irish Latte', 8, N'İrish aromasıyla sıcak, yumuşak içimli latte.', N'Yeni', 180, N'ırısh-latte-sıcakkahve.jpg', 0),
    (N'Latte', 8, N'Espresso ve sütün klasik uyumu; kremamsı içim.', N'Yeni', 170, N'nophoto.jpg', 0),
    (N'Lotus Latte', 8, N'Lotus aromasıyla tatlı ve yumuşak içimli latte.', N'Yeni', 180, N'lotus-latte-sıcakkkahve.jpg', 0),
    (N'Mocha', 8, N'Kahve ve çikolatanın sıcak, yoğun birleşimi.', N'Yeni', 180, N'mocha-sıcakkkahve.jpg', 0),
    (N'Salted Caramel', 8, N'Tuzlu karamel aromasıyla dengeli tatlı bir latte.', N'Yeni', 200, N'saltedcaramel-latte-sıcakkahve.jpg', 0),
    (N'Vanilya Latte', 8, N'Vanilya aromasıyla yumuşak ve tatlı içim.', N'Yeni', 180, N'nophoto.jpg', 0),
    (N'White Mocha', 8, N'Beyaz çikolata dokunuşlu, kremamsı mocha.', N'Yeni', 180, N'white-mocha-sıcakkkahve.jpg', 0),
    (N'Almond Latte', 17, N'Badem aromasıyla hafif ve tatlı latte deneyimi.', N'Yeni', 170, N'almond-latte-specialsıcak.jpg', 0),
    (N'Choco-Banana Latte', 17, N'Çikolata ve muz aromasıyla tatlı, sıcak içim.', N'Yeni', 170, N'choco-banana-latte-specialsıcak.jpg', 0),
    (N'Cocoster Latte', 17, N'Hindistan cevizi aromasıyla yumuşak içimli latte.', N'Yeni', 170, N'cocoster-latte-specialsıcak.jpg', 0),
    (N'Lavender Rose Latte', 17, NULL, N'Yeni', 170, N'lavander-rose-latte-specialsıcak.jpg', 0),
    (N'Pecan Caramel Latte', 17, NULL, N'Yeni', 170, N'pecan-caramel-latte-specialsıcak.jpg', 0),
    (N'Pumpkin Spice Latte', 17, N'Baharatlı balkabağı aromasıyla sıcak ve karakterli içim.', N'Yeni', 170, N'pumpkin-spice-latte-specialsıcak.jpg', 0),
    (N'Quattro Latte', 17, NULL, N'Yeni', 200, N'nophoto.jpg', 0),
    (N'Cold Brew', 9, NULL, N'Yeni', 200, N'cold-brew-sogukkahve.jpg', 0),
    (N'Frappe', 9, NULL, N'Yeni', 220, N'frappe-sogukkahve.jpg', 0),
    (N'Ice Americano', 9, NULL, N'Yeni', 170, N'cold-brew-sogukkahve.jpg', 0),
    (N'Ice Butter Caramel Latte', 9, NULL, N'Yeni', 200, N'ice-caramel-latte-sogukkahve.jpg', 0),
    (N'Ice Caramel Latte', 9, NULL, N'Yeni', 200, N'ice-caramel-latte-sogukkahve.jpg', 0),
    (N'Ice Caramel Macchiato', 9, NULL, N'Yeni', 200, N'ice-caramel-latte-sogukkahve.jpg', 0),
    (N'Ice Cookie Latte', 9, NULL, N'Yeni', 200, N'ice-cookie-latte-sogukkahve.jpg', 0),
    (N'Ice Flat White', 9, NULL, N'Yeni', 190, N'ice-flatwhite-sogukkahve.jpg', 0),
    (N'Ice Hazelnut Latte', 9, NULL, N'Yeni', 200, N'ice-hazelnut-latte-sogukkahve.jpg', 0),
    (N'Ice Irish Latte', 9, NULL, N'Yeni', 200, N'ice-irish-latte-sogukkahve.jpg', 0),
    (N'Ice Latte', 9, NULL, N'Yeni', 180, N'ice-vanilya-latte-sogukkahve.jpg', 0),
    (N'Ice Lotus Latte', 9, NULL, N'Yeni', 200, N'ice-lotus-latte-sogukkahve.jpg', 0),
    (N'Ice Mocha', 9, NULL, N'Yeni', 200, N'ice-mocha-sogukkahve.jpg', 0),
    (N'Ice Salted Caramel Latte', 9, NULL, N'Yeni', 200, N'ice-salted-caramel-latte-sogukkahve.jpg', 0),
    (N'Ice Vanilya Latte', 9, NULL, N'Yeni', 200, N'ice-vanilya-latte-sogukkahve.jpg', 0),
    (N'Ice White Mocha', 9, NULL, N'Yeni', 200, N'ice-white-mocha-sogukkahve.jpg', 0),
    (N'Quattro Affagato', 9, NULL, N'Yeni', 220, N'quattro-affagato-sogukkahve.jpg', 0),
    (N'Çikolatalı Milkshake', 23, NULL, N'Yeni', 180, N'çikolatalı-milkshake.jpg', 0),
    (N'Çilekli Milkshake', 23, NULL, N'Yeni', 180, N'çilekli-milkshake.jpg', 0),
    (N'Karamel Milkshake', 23, NULL, N'Yeni', 180, N'karamel-milkshake.jpg', 0),
    (N'Karpuz Milkshake', 23, NULL, N'Yeni', 180, N'çilekli-milkshake.jpg', 0),
    (N'Ayran', 25, NULL, N'Yeni', 60, N'ayran-meşrubat.jpg', 0),
    (N'Cappy Şeftali', 25, NULL, N'Yeni', 80, N'cappy-şeftali-meşrubat.jpg', 0),
    (N'Cappy Vişne', 25, NULL, N'Yeni', 80, N'cappy-vişne-meşrubat.jpg', 0),
    (N'Coca Cola Kutu', 25, N'Buz gibi servis edilen ferahlatıcı kola.', N'Yeni', 80, N'içecekler-1.jpg', 0),
    (N'Coca Cola Şişe', 25, NULL, N'Yeni', 90, N'coca-cola-şişe-meşrubat.jpg', 0),
    (N'Coca Cola Zero Kutu', 25, NULL, N'Yeni', 80, N'coca-cola-zero-meşrubat.jpg', 0),
    (N'Elmalı Soda', 25, NULL, N'Yeni', 65, N'elmalı-soda-meşrubat.jpg', 0),
    (N'Fanta', 25, N'Portakal aromalı, serinletici gazlı içecek.', N'Yeni', 80, N'içecekler-2.jpg', 0),
    (N'Fuse Tea Karpuz', 25, N'Yaz ferahlığı sunan karpuz aromalı soğuk çay.', N'Yeni', 70, N'içecekler-5.jpg', 0),
    (N'Fuse Tea Mango ve Ananas Kutu', 25, N'Egzotik mango aromalı soğuk çay.', N'Yeni', 70, N'içecekler-4.jpg', 0),
    (N'Fuse Tea Şeftali', 25, N'Doğal şeftali aromasıyla hafif ve ferah.', N'Yeni', 70, N'içecekler-6.jpg', 0),
    (N'Fuse Tea Limon', 25, NULL, N'Yeni', 50, N'içecekler-7.jpg', 0),
    (N'Karpuz Çilek Soda', 25, NULL, N'Yeni', 65, N'karpuzlu-soda-meşrubat.jpg', 0),
    (N'Limonlu Soda', 25, NULL, N'Yeni', 65, N'limonlu-soda-meşrubat.jpg', 0),
    (N'Mango Ananas Soda', 25, NULL, N'Yeni', 65, N'mango-ananas-soda-meşrubat.jpg', 0),
    (N'Premium Sade Soda', 25, NULL, N'Yeni', 90, N'premium-soda-meşrubat.jpg', 0),
    (N'Redbull', 25, NULL, N'Yeni', 110, N'redbull-meşrubat.jpg', 0),
    (N'Sade Soda', 25, NULL, N'Yeni', 60, N'içecekler-8.jpg', 0),
    (N'Sprite Kutu', 25, NULL, N'Yeni', 80, N'sprite-meşrubat.jpg', 0),
    (N'Uludağ Premium Su', 25, NULL, N'Yeni', 50, N'uludağ-premium-su-meşrubat.jpg', 0),
    (N'Berry Hibiscus', 22, NULL, N'Yeni', 180, N'berry-hibiscus-sogukicecek.jpg', 0),
    (N'Blue Ocean', 22, NULL, N'Yeni', 200, N'blue-ocean-sogukicecek.jpg', 0),
    (N'Churchill', 22, NULL, N'Yeni', 120, N'churcill-sogukicecek.jpg', 0),
    (N'Cool Lime', 22, NULL, N'Yeni', 180, N'cool-lime-sogukicecek.jpg', 0),
    (N'Filtre Kahve', 22, NULL, N'Yeni', 150, N'filtre-kahve-sogukicecek.jpg', 0),
    (N'Frozen Ananas', 22, NULL, N'Yeni', 180, N'frozen-ananas-sogukicecek.jpg', 0),
    (N'Frozen Çilek', 22, NULL, N'Yeni', 180, N'frozen-çilek-sogukicecek.jpg', 0),
    (N'Frozen Mango', 22, NULL, N'Yeni', 180, N'frozen-mango-sogukicecek.jpg', 0),
    (N'Frozen Yaban Mersini', 22, NULL, N'Yeni', 180, N'frozen-yaban-mersini-sogukicecek.jpg', 0),
    (N'Gökkuşağı Limonata', 22, NULL, N'Yeni', 200, N'gökkusagı-limonata-sogukicecek.jpg', 0),
    (N'Ice Chai Tea Latte', 22, NULL, N'Yeni', 180, N'ice-chai-tea-latte-sogukicecek.jpg', 0),
    (N'Ice Coco Choco', 22, NULL, N'Yeni', 180, N'ice-coco-choco-sogukicecek.jpg', 0),
    (N'Ice Oreo Latte', 22, NULL, N'Yeni', 180, N'ice-oreo-latte-sogukicecek.jpg', 0),
    (N'Ice Ruby Choco', 22, NULL, N'Yeni', 180, N'ice-ruby-choco-sogukicecek.jpg', 0),
    (N'Ice Sütlü Filtre Kahve', 22, NULL, N'Yeni', 160, N'ice-sütlü-filtre-kahve-sogukicecek.jpg', 0),
    (N'Limonata', 22, NULL, N'Yeni', 180, N'limonata-sogukicecek.jpg', 0),
    (N'Meksikan Lime', 22, NULL, N'Yeni', 180, N'mexican-lime-sogukicecek.jpg', 0),
    (N'Passion Lime', 22, NULL, N'Yeni', 180, N'passion-lime-sogukicecek.jpg', 0),
    (N'Portakal Suyu', 22, NULL, N'Yeni', 180, N'portakal-suyu-sogukicecek.jpg', 0),
    (N'Redbul Special', 22, NULL, N'Yeni', 150, N'redbull-special-sogukicecek.jpg', 0),
    (N'Red Velvet Cup', 10, NULL, N'Yeni', 220, N'nophoto.jpg', 0),
    (N'Antep Fıstıklı Velvet Cup', 10, NULL, N'Yeni', 230, N'antep-fıstıklı-cup-tatlı.jpg', 0),
    (N'Antep Rüyası', 10, N'Antep fıstığı ağırlıklı, zengin aromalı özel tatlı.', N'Yeni', 280, N'antep-rüyası-tatlı.jpg', 0),
    (N'Antep San Sebastian', 10, N'Antep fıstığı dokunuşlu San Sebastian; yoğun ve özel.', N'Yeni', 290, N'antep-fıstıklı-sansebastian-tatlı.jpg', 0),
    (N'Belçika Çikolatalı Pasta', 10, N'Yoğun Belçika çikolatası ile zengin, yumuşak pasta dilimi.', N'Yeni', 260, N'belçika-çikolatalı-tatlı.jpg', 0),
    (N'Bellavista', 10, N'Kremamsı dokusu ve hafif tadıyla özel tatlı seçeneği.', N'Yeni', 220, N'bellvista-tatlı.jpg', 0),
    (N'Red Velvet Pasta', 10, NULL, N'Yeni', 240, N'nophoto.jpg', 0),
    (N'Havuçlu Tarçınlı Pasta', 10, NULL, N'Yeni', 240, N'nophoto.jpg', 0),
    (N'Devil Mono Pasta', 10, N'Yoğun çikolata severlere özel, tek porsiyon mono pasta.', N'Yeni', 280, N'devilmono-tatlı.jpg', 0),
    (N'Extra Callebaut', 10, NULL, N'Yeni', 80, N'extra-callebaut-tatlı.jpg', 0),
    (N'Frambuaz Cheesecake', 10, N'Frambuaz aromasıyla ferah, kremalı cheesecake dilimi.', N'Yeni', 240, N'frambuaz-cheesecake-tatlı.jpg', 0),
    (N'Latte Pasta', 10, N'Kahve aromalı, yumuşak ve dengeli pasta dilimi.', N'Yeni', 260, N'latte-pasta-tatlı.jpg', 0),
    (N'Limon Cheesecake', 10, N'Limonun ferahlığıyla hafif ve kremalı cheesecake.', N'Yeni', 240, N'limon-cheesecake-tatlı.jpg', 0),
    (N'Lotus Cheesake', 10, NULL, N'Yeni', 240, N'lotus-cheesecake-tatlı.jpg', 0),
    (N'Lotus Cheesecake Mono', 10, NULL, N'Yeni', 240, N'lotus-cheesecake-mono-tatlı.jpg', 0),
    (N'Çilekli Magnolia', 10, NULL, N'Yeni', 270, N'çilekli-magnolia-tatlı.jpg', 0),
    (N'Oreo Cheesecake', 10, NULL, N'Yeni', 240, N'oreo-cheesecake-tatlı.jpg', 0),
    (N'San Sebastian', 10, N'Karamelize üst yüzeyiyle klasik San Sebastian cheesecake.', N'Yeni', 240, N'san-sebastian-cheesecake-tatlı.jpg', 0),
    (N'Yaban Mersini Cheesecake', 10, NULL, N'Yeni', 240, N'yaban-mersini-cheesecake-tatlı.jpg', 0),
    (N'Yer Fıstıklı Mono', 10, NULL, N'Yeni', 280, N'yerfstıklı-cheesecake-mono-tatlı.jpg', 0),
    (N'Malaga', 10, NULL, N'Yeni', 300, N'nophoto.jpg', 0),
    (N'Ekler Porsiyon', 10, NULL, N'Yeni', 150, N'nophoto.jpg', 0),
    (N'Spangle', 10, NULL, N'Yeni', 250, N'nophoto.jpg', 0),
    (N'Profiterol', 10, NULL, N'Yeni', 250, N'nophoto.jpg', 0),
    (N'İzmir Bomba', 10, NULL, N'Yeni', 80, N'nophoto.jpg', 0),
    (N'Ceviz Tarçın Çikolatalı Newyork Kurabiye', 10, NULL, N'Yeni', 120, N'nophoto.jpg', 0),
    (N'4-6 Kişilik Pasta', 10, NULL, N'Yeni', 700, N'nophoto.jpg', 0),
    (N'Bademki Kavala Kurabiye Porsiyon', 10, NULL, N'Yeni', 150, N'nophoto.jpg', 0),
    (N'Frambuazlı Fındıklı Mini Tart Porsiyon', 10, NULL, N'Yeni', 180, N'nophoto.jpg', 0),
    (N'Tadelle Kurabiye Porsiyon ', 10, NULL, N'Yeni', 150, N'nophoto.jpg', 0),
    (N'Ay Çekirdekli Kruvasan', 7, NULL, N'Yeni', 150, N'ay-cekirdekli-kruvasan.jpg', 0),
    (N'Balkan Çöreği', 7, NULL, N'Yeni', 150, N'nophoto.jpg', 0),
    (N'Çikolatalı Meyveli Kruvasan', 7, N'Tereyağlı kruvasan arasında taze çilek ve muz dilimleri eşliğinde lezzetli bir kakaolu fındık kreması üzerinde ise nefis Belçika çikolatası.', N'Yeni', 360, N'çikolatalı-meyveli-kruvasan.jpg', 0),
    (N'Guacamole Soslu Ton Balıklı Kruvasan', 7, N'Tereyağlı kruvasan arasında kremaması gucamole taze dilim avokado ve hafif mayonezli özel soslu ton balığı üzerinde mor soğan ve taze roka yaprakları ile servis edilir.', N'Yeni', 335, N'guacanale-soslu-tonbalıklı-kruvasan.jpg', 0),
    (N'Hindi Fümeli Kruvasan', 7, N'Tereyağlı kruvasan arasında ince dilimlenmiş hindi füme cheddar peyniri, taze marul, ve ballı hardal sos ile servis edilir.', N'Yeni', 295, N'hindü-fümeli-kruvasan.jpg', 0),
    (N'Küçük Kruvasan', 7, NULL, N'Yeni', 50, N'küçük-kruvasan.jpg', 0),
    (N'Peynirli Kruvasan', 7, N'Tereyağlı kruvasan arasında kremamsı labne, kaşar peyniri, tulum peyniri ve beyaz peynirin üzerinde domates ve roka yaprakları ile servis edilir.', N'Yeni', 265, N'peynirli-kruvasan.jpg', 0),
    (N'Tereyağlı Sade Kruvasan', 7, N'Tereyağlı kruvasan arasında ince dilimlenmiş hindi füme cheddar peyniri, taze marul, ve ballı hardal sos ile servis edilir.', N'Yeni', 150, N'tereyaglı-sade-kruvasan.jpg', 0),
    (N'Alaturka Gözleme', 14, N'Taze yufka arasında rende kaşar peyniri, sucuk ve renkli biberler, yanında söğüş(domates,salatalık,zeytin), patates cips ve dip sos ile servis edilir.', N'Yeni', 290, N'alaturka-gözleme.jpg', 0),
    (N'Bolu Usulü Gözleme', 14, N'Taze yufka arasında rende kaşar peyniri, kıyma, köz patlıcan, yanında söğüş(domates,salatalık,zeytin) , patates cips ve dip sos ile servis edilir.', N'Yeni', 350, N'bolu-usülü-gözleme.jpg', 0),
    (N'Kaşarlı Gözleme', 14, N'Taze yufka arasında rende kaşar peyniri yanında söğüş(domates, salatalık, zeytin), patates cips ve dip sos ile servis edilir.', N'Yeni', 250, N'kaşarlı-gözleme.jpg', 0),
    (N'Mantarlı Kaşarlı Gözleme', 14, N'Taze yufka arasında rende kaşar peyniri ve mantar dilimleri yanında söğüş(domates,salatalık,zeytin), patates cips ve dip sos ile servis edilir.', N'Yeni', 275, N'mantarlı-kaşarlı-gözleme.jpg', 0),
    (N'Patatesli Gözleme', 14, NULL, N'Yeni', 250, N'patatesli-gözleme.jpg', 0),
    (N'Peynirli Gözleme', 14, N'Taze yufka arasında rende tulum peyniri, yanında söğüş(domates, salatalık, zeytin), patates cips ve dip sos ile servis edilir.', N'Yeni', 225, N'peynirli-gözleme.jpg', 0),
    (N'BBQ Soslu Tavuk', 1, N'Jülyen tavuk dilimleri, renkli biberler, jülyen mantar, özel barbekü sos, yanında patates püresi, maskolin salata ile servis edilir.', N'En çok satan', 440, N'barbekü-soslu-tavuk-anayemek.jpg', 1),
    (N'Beğendili Köfte', 1, N'Beğendi sos üzerinde ızgara köfte yanında parmak patates ve maskolin salata ile servis edilir.', N'En çok satan', 460, N'cokyakında.jpg', 1),
    (N'Cafe de Paris Soslu Tavuk', 1, N'Jülyen tavuk dilimleri, renkli biberler, jülyen mantar, cafe de paris sos yanında patates püresi, maskolin salata ile servis edilir.', N'En çok satan', 430, N'cafedeparis-soslu-tavuk-anayemek.jpg', 1),
    (N'Et Çökertme', 1, NULL, N'Yeni', 500, N'cokyakında.jpg', 0),
    (N'Izgara Tavuk Pirzola', 1, N'Marine edilmiş ızgara tavuk eti yanında patates püresi, maskolin salata ile servis edilir.', N'En çok satan', 450, N'barbekü-soslu-tavuk-anayemek.jpg', 1),
    (N'Karışık Izgara', 1, N'Marine edilmiş ızgara tavuk eti, ev yapımı kasap köfte, sucuk dilimleri yanında patates püresi, maskolin salata ile servis edilir.', N'En çok satan', 600, N'cokyakında.jpg', 1),
    (N'Kekikli Kremalı Tavuk', 1, N'Jülyen tavuk dilimleri, renkli biberler, jülyen mantar, özel dağ kekikli kremalı sos yanında patates püresi, maskolin salata ile servis edilir.', N'En çok satan', 430, N'kekikli-kremalı-tavuk-anayemek.jpg', 1),
    (N'Köri Soslu Tavuk', 1, N'Jülyen tavuk dilimleri, renkli biberler, jülyen mantar, özel körili kremalı sos yanında patates püresi, maskolin salata ile servis edilir.', N'En çok satan', 430, N'köri-soslu-tavuk-anayemek.jpg', 1),
    (N'Pesto Soslu Tavuk', 1, N'Jülyen tavuk dilimleri, renkli biberler, jülyen mantar, özel kremalı fesleğenli sos yanında patates püresi, maskolin salata ile servis edilir.', N'En çok satan', 440, N'pesto-soslu-tavuk-anayemek.jpg', 1),
    (N'Sweetchili Soslu Tavuk', 1, N'Jülyen tavuk dilimleri, renkli biberler, mısır, özel sos yanında patates püresi, maskolin salata ile servis edilir.', N'En çok satan', 440, N'sweetchili-soslu-tavuk-anayemek.jpg', 1),
    (N'Anne Makarna', 4, N'Haşlanmış penne makarnası domates rendesi ile servis edilir.', N'Yeni', 215, N'anne-makarnası.jpg', 0),
    (N'Çıtır Mantı', 4, N'Haşlanmış dana etli mantılar, derin yağda kızarmış şekilde sarımsaklı yoğurt ve tereyağlı özel sos ile servis edilir.', N'Yeni', 250, N'çıtır-mantı.jpg', 0),
    (N'Ev Mantısı', 4, N'Haşlanmış dana etli mantılar, sarımsaklı yoğurt ve tereyağlı özel sos ile servis edilir.', N'Yeni', 350, N'ev-mantısı.jpg', 0),
    (N'Körili Tavuklu Mantarlı Makarna', 4, N'Haşlanmış penne makarnası, jülyen tavuk dilimleri, jülyen mantar, körili kremalı özel sos ile servis edilir.', N'Yeni', 330, N'pesto-soslu-mantarlı-tavuklu-penne-makarna.jpg', 0),
    (N'Kremalı Mantarlı Tavuklu Makarna', 4, N'Haşlanmış penne makarnası, jülyen tavuk dilimleri, jülyen mantar, kremalı özel sos ile servis edilir.', N'Yeni', 330, N'kremalı-tavuklu-penne-makarna.jpg', 0),
    (N'Penne Arabiata', 4, N'Haşlanmış penne makarnası, zeytin dilimleri, mısır, jalapeño biber, özel arabiata sos ile servis edilir.', N'Yeni', 285, N'penne-arabiata-makarna.jpg', 0),
    (N'Pesto Soslu Kremalı Tavuklu Makarna', 4, N'Haşlanmış penne makarnası, jülyen tavuk dilimleri, jülyen mantar, pesto kremalı özel sos ile servis edilir', N'Yeni', 340, N'pesto-soslu-mantarlı-tavuklu-penne-makarna.jpg', 0),
    (N'Tagliatelle Alfredo', 4, N'Haşlanmış tagliatelle makarnası, jülyen mantar, kremalı özel sos, üzerinde ızgara tavuk ile servis edilir', N'Yeni', 350, N'tagliatalle-alfredo-makarna.jpg', 0),
    (N'Çıtır Tavuklu Salata', 5, N'Taze marul roka ve maydanoz yaprakları küp doğranmış domates ve salatalık dilimleri üzerinde panelenmiş çıtır tavuk parçaları ile servis edilir.', N'En çok satan', 330, N'çıtır-tavuklu-salata.jpg', 1),
    (N'Peynirli Avokado Salatası', 5, N'küp doğranmış avokado beyaz peynir domates salatalık ve mor soğanın muazzam birleşimi nar ekşisi ve zeytinyağı ile servis edilir.', N'Yeni', 310, N'peynirli-avakado-salatası.jpg', 0),
    (N'Sezar Salata', 5, N'Çıtır göbek marullar, kroton ekmek, özel sezar sos, ızgara tavuk dilimleri, çeri domatesler ile servis edilir.', N'Yeni', 340, N'sezar-salata.jpg', 0),
    (N'Ton Balıklı Salata', 5, N'Taze marul roka ve maydanoz yaprakları küp doğranmış domates ve salatalık dilimleri üzerinde ton balığı ile servis edilir.', N'Yeni', 320, N'ton-balıklı-salata.jpg', 0),
    (N'Çıtır Tavuk Wrap', 6, N'Tortilla lavaş arasında çıtır tavuk dilimleri, marul, domates, kornişon turşu, cheddar peyniri yanında patates cips, maskolin salata ve dip sos ile servis edilir.', N'En çok satan', 350, N'çıtır-tavuk-wrap.jpg', 1),
    (N'Et Wrap', 6, NULL, N'Yeni', 350, N'cokyakında.jpg', 0),
    (N'Tavuklu Wrap', 6, N'Tortilla lavaş arasında jülyen tavuk dilimleri, renkli biberler, mantar, rende kaşar peyniri, yanında patates cips, maskolin salata ve dip sos ile servis edilir.', N'Yeni', 340, N'tavuk-wrap.jpg', 0),
    (N'4 Peynirli Tost', 12, N'Tost ekmeği arasında rende kaşar peyniri, cheddar peyniri, beyaz peyniri yanında söğüş(domates,salatalık,zeytin), patates cips ve dip sos ile servis edilir.', N'En çok satan', 265, N'4-peynirli-tost.jpg', 1),
    (N'Bazlama Tost', 12, N'Bazlama ekmeği arasında özel sos, kaşar peyniri, sucuk, yumurta, yanında söğüş(domates,salatalık,zeytin), patates cips ve dip sos ile servis edilir.', N'En çok satan', 290, N'bazlama-tost.jpg', 1),
    (N'Kaşarlı Tost', 12, NULL, N'Yeni', 225, N'kaşarlı-tost.jpg', 0),
    (N'Sucuklu Kaşarlı Tost', 12, N'Tost ekmeği arasında rende kaşar peyniri ve sucuk dilimleri yanında söğüş(domates,salatalık,zeytin), patates cips ve dip sos ile servis edilir.', N'En çok satan', 250, N'sucuklu-kaşarlı-tost.jpg', 1),
    (N'Sucuklu Tost', 12, N'Tost ekmeği arasında sucuk dilimleri yanında söğüş(domates,salatalık,zeytin), patates cips ve dip sos ile servis edilir.', N'En çok satan', 225, N'sucuklu-tost.jpg', 1),
    (N'Tulum Peynirli Sucuklu Tost', 12, N'Tost ekmeği arasında rende tulum ve sucuk dilimleri, yanında söğüş(domates,salatalık,zeytin), patates cips ve dip sos ile servis edilir.', N'Yeni', 290, N'sucuklu-tulum-peynirli-tost.jpg', 0),
    (N'Tulum Peynirli Tost', 12, N'Tost ekmeği arasında rende tulum peyniri, yanında söğüş(domates,salatalık,zeytin), patates cips ve dip sos ile servis edilir.', N'Yeni', 265, N'tulum-peynirli-tost.jpg', 0),
    (N'Et Bazlama', 13, NULL, N'Yeni', 500, N'cokyakında.jpg', 0),
    (N'Tavuk Bazlama', 13, N'Bazlama ekmeği arasında domates soslu jülyen tavuk dilimleri, renkli biberler, mantar, bazlama ekmeği üzerinde beşamel sos ve rende kaşar peyniri, yanında patates cips, dip sos ve maskolin salata ile servis edilir.', N'En çok satan', 390, N'tavuk-bazlama.jpg', 1),
    (N'Berry Yogurt Bowl', 11, N'Yoğurt bal ve chia tohumu ile hazırlanır üzerinde yaban mersini ve çilek parçaları ile servis edilir.', N'Yeni', 275, N'berry-yogurt-bowl.jpg', 0),
    (N'Green Detox Bowl', 11, N'Muz , yeşil elma ıspanak ve Hindistan cevizi sütünün muhteşem uyumu ile hazırlanır. Üzerinde chia tohumu kabak çekirdeği ve granola ile servis edilir.', N'En çok satan', 265, N'green-detox-bowl.jpg', 1),
    (N'Peanut Banana Bowl', 11, N'Badem sütü, fıstık ezmesi, muz ve kakao ile hazırlanan protein değeri yüksek bir öğündür. Üzerinde muz dilimleri, gronala ve fıstık kırıkları ile servis edilir.', N'Yeni', 275, N'peabut-banana-bowl.jpg', 0),
    (N'Tropikal Energy Bowl', 11, N'Özenle hazırlanan orman meyveli yoğurdun üzerinde ananas muz çilek ve file badem parçaları ile servis edilir.', N'Yeni', 275, N'tropikal-energy-bowl.jpg', 0),
    (N'Express Kahvaltı (Büyük)', 2, N'Pratik ve doyurucu express kahvaltı tabağı.', N'Yeni', 300, N'nophoto.jpg', 0),
    (N'Express Kahvaltı (Küçük)', 2, N'Hafif express kahvaltı tabağı.', N'Yeni', 200, N'nophoto.jpg', 0),
    (N'Menemen', 2, N'Domates, biber ve yumurta ile hazırlanan klasik menemen.', N'Yeni', 210, N'menemen-kahvaltı.jpg', 0),
    (N'Sahanda Sucuk', 2, N'Sahanda pişirilmiş sucuk porsiyonu.', N'Yeni', 190, N'sahanda-sucuk-kahvaltı.jpg', 0),
    (N'Sahanda Yumurta', 2, N'Sahanda pişirilmiş yumurta porsiyonu.', N'Yeni', 130, N'sahanda-yumurta-kahvaltı.jpg', 0),
    (N'Sucuklu Kaşarlı Menemen', 2, N'Sucuk ve kaşar ile zenginleştirilmiş menemen.', N'Yeni', 250, N'sucuklu-kaşarlı-menemen-kahvaltı.jpg', 0),
    (N'Sucuklu Yumurta', 2, N'Sucuk eşliğinde sahanda yumurta.', N'Yeni', 160, N'sucuklu-yumurta-kahvaltı.jpg', 0),
    (N'Sıcak Kahvaltı', 2, NULL, N'Yeni', 370, N'sıcak-kahvaltı.jpg', 0),
    (N'Ekstra Krema', 19, N'İçeceklerinize ekstra krema ekleyin.', N'Yeni', 25, N'krema-ekstralar.jpg', 0),
    (N'Ekstra Shot', 19, N'Kahvenize ekstra espresso shot ekleyin.', N'Yeni', 30, N'espresso-ekstralar.jpg', 0),
    (N'Ekstra Süt', 19, N'İçeceklerinize ekstra süt ekleyin.', N'Yeni', 25, N'süt-ekstralar.jpg', 0),
    (N'Ekstra Şurup', 19, N'Aromalı şurup ilavesi.', N'Yeni', 30, N'şurup-ekstralar.jpg', 0),
    (N'Küçük Sakız', 19, N'Tekli küçük sakız.', N'Yeni', 30, N'sakız-ekstralar.jpg', 0),
    (N'Lolipop', 19, N'Tekli lolipop.', N'Yeni', 30, N'lolipop-ekstralar.jpg', 0),
    (N'Mentos', 19, N'Mentos şekerleme.', N'Yeni', 50, N'mentos-ekstralar.jpg', 0),
    (N'Vividend Sakız', 19, N'Vividend sakız.', N'Yeni', 80, N'vivident-ekstralar.jpg', 0),
    (N'Taşıma Çantası', 19, N'Take away kahveler için taşıma çantası.', N'Yeni', 10, N'nophoto.jpg', 0),
    (N'Laktozsuz Süt', 19, NULL, N'Yeni', 25, N'nophoto.jpg', 0),
    (N'3 Top Dondurma', 20, N'3 top dondurma seçeneği.', N'Yeni', 100, N'üçlü-dondurma.jpg', 0),
    (N'Bal Badem Top', 20, N'Bal badem aromalı 1 top.', N'Yeni', 40, N'bal-badem-dondurma.jpg', 0),
    (N'Blue Sky Top', 20, N'Blue sky aromalı 1 top.', N'Yeni', 40, N'blue-sky-dondurma.jpg', 0),
    (N'Bubble Gum Top', 20, N'Bubble gum aromalı 1 top.', N'Yeni', 40, N'bubble-gum-dondurma.jpg', 0),
    (N'Çikolata Kaymak Top', 20, N'Çikolata-kaymak aromalı 1 top.', N'Yeni', 40, N'çikolata-kaymaklı-dondurma.jpg', 0),
    (N'Çilek Top', 20, N'Çilek aromalı 1 top.', N'Yeni', 40, N'çilekli-dondurma.jpg', 0),
    (N'Karadut Top', 20, N'Karadut aromalı 1 top.', N'Yeni', 40, N'karadut-dondurma.jpg', 0),
    (N'Karamel Top', 20, N'Karamel aromalı 1 top.', N'Yeni', 40, N'karamel-dondurma.jpg', 0),
    (N'Kavun Top', 20, N'Kavun aromalı 1 top.', N'Yeni', 40, N'kavun-dondurma.jpg', 0),
    (N'Limon Top', 20, N'Limon aromalı 1 top.', N'Yeni', 40, N'limonlu-dondurma.jpg', 0),
    (N'Oreo Top', 20, N'Oreo aromalı 1 top.', N'Yeni', 40, N'oreo-dondurma.jpg', 0),
    (N'Vanilya Top', 20, N'Vanilya aromalı 1 top.', N'Yeni', 40, N'vanilya-dondurma.jpg', 0),
    (N'Siyah Çay', 24, N'Sıcak çay.', N'Yeni', 50, N'siyahçay-çay.jpg', 0),
    (N'Fincan Siyah Çay', 24, N'Fincanda Sıcak çay.', N'Yeni', 90, N'fincan-siyahçay-çay.jpg', 0),
    (N'Kupa Siyah Çay ', 24, N'Kupada Sıcak çay.', N'Yeni', 120, N'kupa-siyahçay-çay.jpg', 0),
    (N'Ada Çayı', 24, N'Sıcak ada çayı.', N'Yeni', 130, N'adaçayı-çay.jpg', 0),
    (N'Böğürtlen Çayı', 24, N'Sıcak böğürlen çayı.', N'Yeni', 130, N'böğürtlençayı-çay.jpg', 0),
    (N'Hibiscus Çayı', 24, N'Sıcak hibiscus çayı.', N'Yeni', 130, N'hibiscus-çay.jpg', 0),
    (N'Ihlamur', 24, N'Sıcak ıhlamur çayı.', N'Yeni', 130, N'ıhlamur-çay.jpg', 0),
    (N'Kış Çayı', 24, N'Kış çayı karışımı.', N'Yeni', 130, N'kışçayı-çay.jpg', 0),
    (N'Kuş Burnu', 24, N'Sıcak kuşburnu çayı.', N'Yeni', 130, N'kuşburnu-çay.jpg', 0),
    (N'Nane Limon', 24, N'Sıcak nane limon.', N'Yeni', 130, N'nane-limon-çay.jpg', 0),
    (N'Papatya Çayı', 24, N'Sıcak papatya çayı.', N'Yeni', 130, N'papatya-çay.jpg', 0),
    (N'Quattro Special', 24, N'Özel karışım bitki çayı.', N'Yeni', 150, N'papatya-çay.jpg', 0),
    (N'Yasemin Çay', 24, N'Sıcak yasemin çayı.', N'Yeni', 130, N'yasemin-çay.jpg', 0),
    (N'Yeşil Çay', 24, N'Sıcak yeşil çay.', N'Yeni', 130, N'yeşil-çay.jpg', 0),
    (N'Ice Almond Latte', 18, N'Buzlu badem aromalı latte.', N'Yeni', 220, N'ice-almondlatte-specialsoguk.jpg', 0),
    (N'Ice Choco-Banana Latte', 18, N'Buzlu çikolata-muz aromalı latte.', N'Yeni', 220, N'ice-choco-banana-latte-specialsoguk.jpg', 0),
    (N'Ice Cocoster Latte', 18, N'Buzlu hindistan cevizi aromalı latte.', N'Yeni', 220, N'ice-cocoster-specialsoguk.jpg', 0),
    (N'Ice Pecan Caramel Latte', 18, N'Buzlu pekan-karamel aromalı latte.', N'Yeni', 220, N'ice-pecan-caramel-specialsoguk.jpg', 0),
    (N'Ice Pumpkin Spice Latte', 18, N'Buzlu pumpkin spice latte.', N'Yeni', 200, N'ice-pumpkin-spice-latte-specialsoguk.jpg', 0),
    (N'Ice Quattro Latte', 18, NULL, N'Yeni', 220, N'nophoto.jpg', 0),
    (N'Karışık Pizza Menü', 15, N'Karışık pizza menü seçeneği.', N'Yeni', 250, N'cokyakında.jpg', 0),
    (N'Tiftik Burger', 3, N'Özel tiftik burger (fotoğraftaki ürün).', N'Yeni', 520, N'cokyakında.jpg', 0),
    (N'Hawai Burger', 3, N'Izgara burger köftesi,  özel soslu mushroom mantar, cheddar sos, karamelize soğan yanında patates cips ve dip sos ile servis edilir.', N'En çok satan', 460, N'hawai-burger.jpg', 1),
    (N'Smash Burger', 3, N'Double ızgara burger köftesi cheddar sos, karamelize soğan, yanında patates cips ve dip sos ile servis edilir.', N'En çok satan', 610, N'smash-burger.jpg', 1),
    (N'Miami Burger', 3, N'Izgara burger köftesi, karamelize soğan, mayonezli isli köz patlıcan, rosebeef dilimleri yanında patates cips ve dip sos ile servis edilir.', N'En çok satan', 460, N'miami-burger.jpg', 1),
    (N'Çıtır Tavuk Burger', 3, N'Panelenmiş çıtır tavuk pirzola, kornişon turşu, cheddar sos, karamelize soğan, coleslaw salata, yanında  patates cips ve dip sos ile servis edilir.', N'En çok satan', 350, N'çıtır-tavuk-burger.jpg', 1),
    (N'Sıcak Çikolata', 21, N'Yoğun kakao aromalı sıcak çikolata.', N'Yeni', 180, N'sıcak-çikolata-sıcakiçecek.jpg', 0),
    (N'Filtre Kahve', 21, NULL, N'Yeni', 130, N'nophoto.jpg', 0),
    (N'Sütlü Filtre Kahve', 21, N'Yumuşak içimli sütlü filtre kahve.', N'Yeni', 140, N'sütlü-filtre-kahve-sıcakiçecek.jpg', 0),
    (N'Türk Kahvesi (Az Şekerli)', 21, N'Az şekerli geleneksel Türk kahvesi.', N'Yeni', 120, N'türk-kahvesi-sıcakiçecek.jpg', 0),
    (N'Türk Kahvesi (Orta)', 21, N'Orta şekerli geleneksel Türk kahvesi.', N'Yeni', 120, N'türk-kahvesi-sıcakiçecek.jpg', 0),
    (N'Türk Kahvesi (Sade)', 21, N'Şekersiz geleneksel Türk kahvesi.', N'Yeni', 120, N'türk-kahvesi-sıcakiçecek.jpg', 0),
    (N'Türk Kahvesi (Şekerli)', 21, N'Şekerli geleneksel Türk kahvesi.', N'Yeni', 120, N'türk-kahvesi-sıcakiçecek.jpg', 0),
    (N'Double Türk Kahvesi', 21, N'Daha yoğun lezzet isteyenler için double Türk kahvesi.', N'Yeni', 160, N'double-türk-kahvesi-sıcakiçecekler.jpg', 0),
    (N'Osmanlı Kahvesi', 21, N'Daha yoğun lezzet isteyenler için double Türk kahvesi.', N'Yeni', 120, N'osmanlı-kahvesi-sıcakiçecek.jpg', 0),
    (N'Menengiç Kahvesi', 21, N'Daha yoğun lezzet isteyenler için double Türk kahvesi.', N'Yeni', 120, N'menengiç-kahvesi-sıcakiçecek.jpg', 0),
    (N'Bonfrit', 16, N'Kızarmış baharatlı parmak patatesler, dip sos ile servis edilir.', N'Yeni', 180, N'patates-atıştırmalık.jpg', 0),
    (N'Çıtır Tavuk', 16, N'Kızarmış paneli çıtır tavuk parçaları, patates cips ve dip sos ile servis edilir.', N'Yeni', 330, N'çıtır-tavuk-atıştırmalık.jpg', 0),
    (N'Karışık Sepet', 16, N'Sigara böreği, sosis, soğan halkası, çıtır tavuk, patates cips ve dip sos ile servis edilir.', N'Yeni', 390, N'karışık-sepet-atıştırmalık.jpg', 0),
    (N'Sigara Böreği', 16, N'Kızarmış sigara börekleri, patates cips ve dip sos ile servis edilir.', N'Yeni', 220, N'sigara-böreği-atıştırmalık.jpg', 0),
    (N'Soğan Halkası', 16, N'Panelenmiş çıtır soğan, patates cips ve dip sos ile servis edilir.', N'Yeni', 220, N'soğan-halkası-atıştırmalık.jpg', 0)
    ) AS raw (ProductName, CategoryId, Description, Tooltip, Price, Image, IsFeatured)
    CROSS JOIN (
        SELECT
            MAX(CASE WHEN c.name = N'ProductName' THEN CASE WHEN t.name IN (N'nchar', N'nvarchar') AND c.max_length <> -1 THEN c.max_length / 2 WHEN c.max_length = -1 THEN 4000 ELSE c.max_length END END) AS ProductNameMax,
            MAX(CASE WHEN c.name = N'Description' THEN CASE WHEN t.name IN (N'nchar', N'nvarchar') AND c.max_length <> -1 THEN c.max_length / 2 WHEN c.max_length = -1 THEN 4000 ELSE c.max_length END END) AS DescriptionMax,
            MAX(CASE WHEN c.name = N'Tooltip' THEN CASE WHEN t.name IN (N'nchar', N'nvarchar') AND c.max_length <> -1 THEN c.max_length / 2 WHEN c.max_length = -1 THEN 4000 ELSE c.max_length END END) AS TooltipMax,
            MAX(CASE WHEN c.name = N'Image' THEN CASE WHEN t.name IN (N'nchar', N'nvarchar') AND c.max_length <> -1 THEN c.max_length / 2 WHEN c.max_length = -1 THEN 4000 ELSE c.max_length END END) AS ImageMax
        FROM sys.columns AS c
        INNER JOIN sys.types AS t
            ON c.user_type_id = t.user_type_id
        WHERE c.object_id = OBJECT_ID(N'dbo.Products')
    ) AS lengths
) AS source
ON target.ProductName = source.ProductName AND target.CategoryId = source.CategoryId
WHEN MATCHED AND (
    ISNULL(target.Description, N'') <> ISNULL(source.Description, N'')
    OR ISNULL(target.Tooltip, N'') <> ISNULL(source.Tooltip, N'')
    OR target.Price <> source.Price
    OR ISNULL(target.Image, N'') <> ISNULL(source.Image, N'')
    OR ISNULL(target.IsFeatured, 0) <> source.IsFeatured
) THEN UPDATE SET
    target.Description = source.Description,
    target.Tooltip = source.Tooltip,
    target.Price = source.Price,
    target.Image = source.Image,
    target.IsFeatured = source.IsFeatured
WHEN NOT MATCHED BY TARGET THEN
    INSERT (ProductName, CategoryId, Description, Tooltip, Price, Image, IsFeatured)
    VALUES (source.ProductName, source.CategoryId, source.Description, source.Tooltip, source.Price, source.Image, source.IsFeatured);

COMMIT TRANSACTION;

-- Source rows: 
241
-- Merge rows: 
239
-- Skipped: 
meyve-tabagi|Karışık Çerez; meyve-tabagi|Meyve Tabağı
